### ISSUE TITLE
Don't abbrieviate product name?

### ISSUE THREAD

**Issue by rchl** [Sublime-Instincts/CommandsBrowser#5]
I feel that using `ST` and `SM` abbreviations could potentially sound cryptic to some:

https://github.com/Sublime-Instincts/CommandsBrowser/blob/f64739d3d59f4f1362751b9dabf83a1bc0722461/resources/CommandsBrowser.sublime-commands#L3-L15

Maybe use full product names - `Sublime Text` and `Sublime Merge` instead?

**Comment by Ultra-Instinct-05** [comment]
I don't have a strong opinion on this one as it's a Sublime Text specific package and is not that difficult to understand what ST & SM stand for, but sure, I can change it to `Sublime Text` and `Sublime Merge`. The more explicit, the better.

**Comment by Ultra-Instinct-05** [comment]
Should be fixed in the referenced commit & will be available when a new tagged release comes out. Will close once the next tagged release is out.

**Comment by Ultra-Instinct-05** [comment]
Fixed in `v1.1.0`
