### ISSUE TITLE
Use color-based instead of semantic kind IDs for the command type icons

### ISSUE THREAD

**Issue by jwortmann** [Sublime-Instincts/CommandsBrowser#6]
### Description of your enhancement/feature request proposal.

Hi, thanks for the package, it is really convenient during plugin development!

I'd like to ask for the following enhancement:
For the kind icons of the items in the panel, you use kind IDs like for example `sublime.KIND_ID_FUNCTION`, which are supposed to represent things like the type of certain tokens in the program code or the item type for autocompletions:
https://github.com/Sublime-Instincts/CommandsBrowser/blob/154c180e5f30a48fa84ba1fd8c518d7813a78d5a/src/utils/miscellaneous_utils.py#L18-L28

In my theme (https://github.com/jwortmann/brackets-theme), this results in showing certain icons instead of the usual letters for the different command types. But here, those icons / semantic kind IDs don't make much sense, because I wouldn't really say that for example a text command corresponds to "namespace" or a window command to "function".

![icons](https://user-images.githubusercontent.com/6579999/151896481-dfa01656-5440-454b-97c7-95a367631fff.png)

Would it be possible that you change the kind IDs to use the "color-based" kind IDs, for example `sublime.KIND_ID_COLOR_REDISH`, etc., see https://www.sublimetext.com/docs/api_reference.html#type-kind_tuple at the bottom of the section.

In that case, the kind icons would be shown as letters with the specified colors even in my theme, like in the following screenshot :slightly_smiling_face:

![colors](https://user-images.githubusercontent.com/6579999/151897346-21b5c1f3-fdc2-4d34-a89c-58a057ea6527.png)

### Alternatives.

:shrug:

**Comment by Ultra-Instinct-05** [comment]
I have published `v1.4.0` to address this (& have also checked with `Brackets` theme if it's working, which it does on my side). Please confirm when you have some time to check it.

**Comment by jwortmann** [comment]
Thanks, it works great now!
