### ISSUE TITLE
Limited functionality when installed to Sublime Merge

### ISSUE THREAD

**Issue by dragos240** [Sublime-Instincts/CommandsBrowser#8]
### Description of the bug

When installing to Sublime Merge by cloning the repo in `~/.config/sublime-merge/Packages`, then restarting the application, I only see the following commands:
- CommandsBrowser: Open Wiki.
- CommandsBrowser: View Documentation

![image](https://github.com/Sublime-Instincts/CommandsBrowser/assets/704081/ed4cbd98-5142-4177-8fce-84855dfec17e)

I do not see the ability to view Sublime Merge commands within Sublime Merge. However, when I install it into Sublime Text (via Package Control), I can see Sublime Merge commands

### Steps to reproduce

- Open terminal/shell and `cd` to `~/.config/sublime-merge/Packages`
- Clone repository
- Close Sublime Merge (if it was open)
- Open Sublime Merge
- Open command palette and type in `CommandsBrowser`

### Expected behavior

I should see an option to view Sublime Merge commands

### Actual behavior

I only see those two options, but not an option to view Sublime Merge commands

### CommandsBrowser version

16ef299

**Comment by Ultra-Instinct-05** [comment]
Closing this as this is the intended behavior.
